// Icebreak — seed data for the interface.
// Ported verbatim from the Claude Design prototype (mock-data.js).
// Stage 2 replaces this module with the scraping + scoring API.
import type {
  Criterion,
  CriterionOutcome,
  CriterionResult,
  CriterionType,
  Evidence,
  EvidenceSource,
  Guidance,
  Lead,
  SampleLead,
  StarterCriterion,
} from "./types";

const C = {
  team: 'Team size 10–200',
  pain: 'Manual-process pain point',
  hiring: 'Hiring sales or SDR roles',
  outbound: 'Runs outbound already',
  b2b: 'Sells to other businesses',
  agency: 'Staffing or recruiting agency',
  funding: 'Raised in the last 18 months',
};

export const criteria: Criterion[] = [
  {
    id: 'cr_team', name: C.team, type: 'must_have', weight: 5, source: 'both', enabled: true,
    description: 'Employee count on the LinkedIn company page, or a team/about page on the site. Under 10 people there is usually no SDR to sell to.',
  },
  {
    id: 'cr_b2b', name: C.b2b, type: 'must_have', weight: 5, source: 'website', enabled: true,
    description: 'Pricing, case studies or customer logos aimed at companies rather than consumers.',
  },
  {
    id: 'cr_pain', name: C.pain, type: 'must_have', weight: 4, source: 'website', enabled: true,
    description: 'Site copy names a repetitive manual workflow — copy-pasting between tools, spreadsheets, chasing updates by email.',
  },
  {
    id: 'cr_hiring', name: C.hiring, type: 'nice_to_have', weight: 3, source: 'linkedin', enabled: true,
    description: 'Open SDR, AE or revenue roles posted in the last 90 days. Hiring means the outbound motion is being rebuilt right now.',
  },
  {
    id: 'cr_outbound', name: C.outbound, type: 'nice_to_have', weight: 2, source: 'both', enabled: true,
    description: 'Named SDRs on LinkedIn, a sequencing tool in the site footer, or a "book a demo" path that assumes cold traffic.',
  },
  {
    id: 'cr_agency', name: C.agency, type: 'disqualifier', weight: null, source: 'both', enabled: true,
    description: 'Staffing, recruiting and creative resourcing shops resell this category and churn inside two quarters.',
  },
  {
    id: 'cr_funding', name: C.funding, type: 'nice_to_have', weight: 2, source: 'linkedin', enabled: false,
    description: 'Funding announcement on the company page. Useful signal, but it pushed the score around too much, so it is off for now.',
  },
];

export const guidance: Guidance = {
  tone: 'Direct',
  maxLength: 320,
  instruction: 'Always reference something specific from their site. Never mention their funding round.',
};

const cr = (
  criterion: string,
  type: CriterionType,
  weight: number | null,
  result: CriterionResult,
  note: string,
): CriterionOutcome => ({ criterion, type, weight, result, note });
const ev = (
  source: EvidenceSource,
  location: string,
  snippet: string,
  supports: string[],
): Evidence => ({ source, location, snippet, supports });

export const leads: Lead[] = [
  {
    id: 'ld_2a57', fullName: 'Nadia Osei', email: 'nadia@kelpanalytics.com', phone: '+1 (206) 555-0193',
    companyWebsite: 'https://kelpanalytics.com', linkedinUrl: 'https://linkedin.com/company/kelp-analytics',
    companyName: 'Kelp Analytics', role: 'VP Marketing', niche: 'B2B SaaS — supply chain analytics',
    primaryService: 'Inventory forecasting for mid-market distributors',
    icpFitScore: 10, status: 'scored', scoredAt: '2026-08-28T09:41:00Z', durationMs: 5100, criteriaVersion: 'v4',
    icpFitReason: 'Every must-have is met outright: 88 employees, sells only to distributors, and the homepage opens on the exact spreadsheet workflow we replace. Two open SDR roles and a named outbound team on top.',
    icebreaker: 'Your homepage opens with "our customers were forecasting in a 40-tab spreadsheet" — which is roughly what your two new SDRs are about to do with lead research. Worth comparing notes before they ramp?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 88 employees.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Pricing page is per-warehouse, with distributor case studies.'),
      cr(C.pain, 'must_have', 4, 'met', 'Homepage hero names a 40-tab spreadsheet workflow.'),
      cr(C.hiring, 'nice_to_have', 3, 'met', 'Two SDR roles posted 11 days ago.'),
      cr(C.outbound, 'nice_to_have', 2, 'met', 'Four people list "Outbound" in their LinkedIn titles.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Software company, not an agency.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '88 employees · Software Development · Seattle, WA', [C.team]),
      ev('website', 'Homepage — hero', 'Our customers were forecasting in a 40-tab spreadsheet. Now they forecast in a browser tab.', [C.pain, C.b2b]),
      ev('linkedin', 'Jobs — 2 open roles', 'Sales Development Representative · Posted 11 days ago · Seattle (Hybrid)', [C.hiring]),
      ev('website', 'Pricing', '$390 per warehouse / month. Volume terms for 10+ sites.', [C.b2b]),
      ev('linkedin', 'People — filter "outbound"', '4 results · Outbound SDR, Outbound Lead, Sr. Outbound AE, Outbound Ops', [C.outbound]),
    ],
  },
  {
    id: 'ld_8f2a', fullName: 'Jordan Ellis', email: 'jordan@northlight.io', phone: '+1 (415) 555-0148',
    companyWebsite: 'https://northlight.io', linkedinUrl: 'https://linkedin.com/company/northlight',
    companyName: 'Northlight', role: 'Head of Growth', niche: 'B2B SaaS — HR tech',
    primaryService: 'Applicant tracking for mid-market teams',
    icpFitScore: 9, status: 'scored', scoredAt: '2026-08-27T14:22:00Z', durationMs: 4700, criteriaVersion: 'v4',
    icpFitReason: 'Mid-market SaaS with 40–60 employees, hiring 3 SDRs right now, and their site leads with a manual-process pain point our product removes.',
    icebreaker: "Saw you're hiring three SDRs at once off the back of the Series A — that's a lot of ramp happening in parallel. Curious how you're handling lead research for the new reps before they hit quota.",
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 52 employees.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells seats to HR teams; no consumer path.'),
      cr(C.pain, 'must_have', 4, 'met', 'Hero copy is about copy-pasting candidates between tools.'),
      cr(C.hiring, 'nice_to_have', 3, 'met', 'Three SDR openings, all posted this month.'),
      cr(C.outbound, 'nice_to_have', 2, 'partial', 'One SDR on the team page, no sequencing tool detected.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Product company.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '52 employees · Software Development · San Francisco, CA', [C.team]),
      ev('website', 'Homepage — hero', 'Stop copy-pasting candidates between five tools.', [C.pain]),
      ev('linkedin', 'Jobs — 3 open roles', 'SDR (New York) · SDR (Remote, US) · Senior SDR (San Francisco)', [C.hiring]),
      ev('website', 'Customers', 'Used by talent teams at 140+ mid-market companies.', [C.b2b]),
      ev('website', 'About — team grid', '“Ravi K. — Sales Development” is the only sales-side profile listed.', [C.outbound]),
    ],
  },
  {
    id: 'ld_3c71', fullName: 'Priya Raman', email: 'priya@cadencefreight.com', phone: '+1 (312) 555-0102',
    companyWebsite: 'https://cadencefreight.com', linkedinUrl: 'https://linkedin.com/company/cadence-freight',
    companyName: 'Cadence Freight', role: 'VP Revenue', niche: 'Logistics — freight brokerage',
    primaryService: 'Digital freight brokerage for regional carriers',
    icpFitScore: 8, status: 'scored', scoredAt: '2026-08-27T11:05:00Z', durationMs: 5400, criteriaVersion: 'v4',
    icpFitReason: 'Ops-heavy team of 120 selling to carriers, and the site names manual quoting as the problem they exist to fix. No sign of an outbound motion yet, which is why this is an 8 and not a 9.',
    icebreaker: 'Your quoting page says brokers still rebuild the same quote four times a day — I imagine the research your reps do before a cold call looks similar. How are you sourcing carrier context today?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 121 employees.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Customers are carriers and shippers.'),
      cr(C.pain, 'must_have', 4, 'met', '"Rebuild the same quote four times a day" on the product page.'),
      cr(C.hiring, 'nice_to_have', 3, 'met', 'Two Account Executive roles open.'),
      cr(C.outbound, 'nice_to_have', 2, 'not_met', 'No SDR titles, no sequencer, demo form is inbound-shaped.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Brokerage, not a staffing agency.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '121 employees · Truck Transportation · Chicago, IL', [C.team]),
      ev('website', 'Product — Quoting', 'Brokers rebuild the same quote four times a day. We cache it once.', [C.pain]),
      ev('linkedin', 'Jobs — 2 open roles', 'Account Executive · Account Executive (Midwest)', [C.hiring]),
      ev('website', 'Contact', 'Request a demo — a broker will call you back within one business day.', [C.outbound]),
    ],
  },
  {
    id: 'ld_3b90', fullName: 'Lena Fischer', email: 'lena@cobaltledger.com', phone: '+1 (617) 555-0177',
    companyWebsite: 'https://cobaltledger.com', linkedinUrl: 'https://linkedin.com/company/cobalt-ledger',
    companyName: 'Cobalt Ledger', role: 'Head of Revenue', niche: 'Fintech — accounting automation',
    primaryService: 'Month-end close automation for finance teams',
    icpFitScore: 8, status: 'scored', scoredAt: '2026-08-26T16:48:00Z', durationMs: 4900, criteriaVersion: 'v4',
    icpFitReason: 'Clean must-have profile at 64 employees, and the whole site is built around a manual close process. Hiring is quiet, so the nice-to-haves only half land.',
    icebreaker: 'The "day 9 close" number on your homepage is a good hook — it also means your buyers are the same finance leads everyone else is emailing in week one. Curious what you do to get in earlier.',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 64 employees.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells to controllers and finance teams.'),
      cr(C.pain, 'must_have', 4, 'met', '"Close took nine days" comparison table.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'No open sales roles.'),
      cr(C.outbound, 'nice_to_have', 2, 'met', 'Two SDRs listed on LinkedIn.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Software company.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '64 employees · Financial Services · Boston, MA', [C.team]),
      ev('website', 'Homepage — comparison', 'Before Cobalt: close took nine days. After: three.', [C.pain, C.b2b]),
      ev('linkedin', 'People', 'Two profiles titled "Sales Development Representative".', [C.outbound]),
    ],
  },
  {
    id: 'ld_8e31', fullName: 'Ben Ostrowski', email: 'b.ostrowski@haldencoatings.com', phone: '+1 (216) 555-0134',
    companyWebsite: 'https://haldencoatings.com', linkedinUrl: 'https://linkedin.com/company/halden-coatings',
    companyName: 'Halden Coatings', role: 'Sales Director', niche: 'Manufacturing — industrial coatings',
    primaryService: 'Protective coatings for municipal water infrastructure',
    icpFitScore: 7, status: 'scored', scoredAt: '2026-08-26T10:12:00Z', durationMs: 6200, criteriaVersion: 'v4',
    icpFitReason: 'Right size and clearly B2B, but the pain point is inferred from a downloadable spec sheet rather than stated on the site.',
    icebreaker: 'Your spec library is the most detailed I have seen for municipal coatings — and it looks like your reps assemble those PDFs by hand per bid. Is that still the case?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 175 employees.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells to municipalities and contractors.'),
      cr(C.pain, 'must_have', 4, 'partial', 'Implied by the manual bid-packet process, never stated.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'No sales roles posted.'),
      cr(C.outbound, 'nice_to_have', 2, 'partial', 'Field sales team, no SDR function.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Manufacturer.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '175 employees · Chemical Manufacturing · Cleveland, OH', [C.team]),
      ev('website', 'Resources — Spec library', '61 downloadable spec sheets, last updated per project by the regional rep.', [C.pain, C.outbound]),
      ev('website', 'Markets', 'Municipal water, wastewater treatment, bridge and marine.', [C.b2b]),
    ],
  },
  {
    id: 'ld_9f12', fullName: 'Owen Pryce', email: 'owen@sablefreight.tech', phone: '+1 (503) 555-0166',
    companyWebsite: 'https://sablefreight.tech', linkedinUrl: 'https://linkedin.com/company/sable-freight-tech',
    companyName: 'Sable Freight Tech', role: 'Co-founder', niche: 'Logistics — yard management',
    primaryService: 'Yard management software for distribution centres',
    icpFitScore: 7, status: 'scored', scoredAt: '2026-08-25T13:30:00Z', durationMs: 4400, criteriaVersion: 'v4',
    icpFitReason: 'Strong pain point and clearly B2B, but at 14 employees they sit at the bottom edge of the size band and there is no sales team to speak of yet.',
    icebreaker: 'Two of your three case studies open with a yard manager on a walkie-talkie. Guessing your own pipeline research is about that manual right now — how are you picking which DCs to call?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'partial', '14 employees — inside the band, but only just.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells to distribution centres.'),
      cr(C.pain, 'must_have', 4, 'met', 'Case studies open on walkie-talkie coordination.'),
      cr(C.hiring, 'nice_to_have', 3, 'met', 'One "first sales hire" role posted.'),
      cr(C.outbound, 'nice_to_have', 2, 'not_met', 'Founder-led sales only.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Software company.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '14 employees · Software Development · Portland, OR', [C.team]),
      ev('website', 'Case studies', 'Before Sable, the yard ran on two whiteboards and a walkie-talkie.', [C.pain]),
      ev('linkedin', 'Jobs — 1 open role', 'Founding Account Executive · Posted 4 days ago', [C.hiring]),
    ],
  },
  {
    id: 'ld_9b45', fullName: 'Marcus Feld', email: 'marcus.feld@verityhealthsystems.com', phone: '+1 (612) 555-0119',
    companyWebsite: 'https://verityhealthsystems.com', linkedinUrl: 'https://linkedin.com/company/verity-health-systems',
    companyName: 'Verity Health Systems', role: 'Director of Clinical Operations', niche: 'Healthcare — clinical ops',
    primaryService: 'Care coordination and referral management software for regional hospital networks and multi-site specialty groups',
    icpFitScore: 6, status: 'scored', scoredAt: '2026-08-25T08:55:00Z', durationMs: 7100, criteriaVersion: 'v4',
    icpFitReason: 'B2B and the right size, but the buying committee is clinical rather than commercial and nothing on the site suggests an outbound motion we can plug into.',
    icebreaker: 'Your referral-tracking page describes faxes being re-keyed by hand, which is a familiar shape of problem. Who owns the commercial side of a rollout like that on your team?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 190 employees.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells to hospital networks.'),
      cr(C.pain, 'must_have', 4, 'partial', 'Faxes mentioned once, in a support article.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'Clinical roles only.'),
      cr(C.outbound, 'nice_to_have', 2, 'not_met', 'No SDR or AE profiles found.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Provider network.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '190 employees · Hospital & Health Care · Minneapolis, MN', [C.team]),
      ev('website', 'Support — Referrals', 'Inbound referral faxes are re-keyed into the EHR by the intake team.', [C.pain]),
      ev('linkedin', 'Jobs — 6 open roles', 'RN Care Manager · Intake Coordinator · Clinical Analyst · 3 more', [C.hiring]),
    ],
  },
  {
    id: 'ld_7a62', fullName: 'Dana Whitfield', email: 'dana@orbitparcel.com', phone: '+1 (702) 555-0188',
    companyWebsite: 'https://orbitparcel.com', linkedinUrl: 'https://linkedin.com/company/orbit-parcel',
    companyName: 'Orbit Parcel', role: 'Head of Partnerships', niche: 'Logistics — last-mile delivery',
    primaryService: 'Same-day last-mile delivery for regional retailers',
    icpFitScore: 5, status: 'needs_review', scoredAt: '2026-08-28T07:19:00Z', durationMs: 9800, criteriaVersion: 'v4',
    unreadableSource: 'linkedin',
    icpFitReason: 'Scored on website evidence only — their LinkedIn page did not respond, so team size and hiring signals are unverified. Everything the site says points to a fit.',
    icebreaker: 'Your coverage map went from four metros to eleven in a year, which usually means the retailer conversations got harder to keep straight. How are you prioritising which accounts to chase next?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'unknown', 'LinkedIn unreachable — no employee count available.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells delivery capacity to retailers.'),
      cr(C.pain, 'must_have', 4, 'met', 'Site names manual dispatch spreadsheets.'),
      cr(C.hiring, 'nice_to_have', 3, 'unknown', 'LinkedIn unreachable — job posts not checked.'),
      cr(C.outbound, 'nice_to_have', 2, 'partial', 'Partnerships page implies outbound; no SDR evidence.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Delivery operator.'),
    ],
    evidence: [
      ev('website', 'Homepage — coverage', 'Eleven metros, up from four last spring.', [C.b2b]),
      ev('website', 'Product — Dispatch', 'Most regional carriers still dispatch out of a shared spreadsheet.', [C.pain]),
      ev('website', 'Partnerships', 'Tell us about your store network and we will find you capacity.', [C.outbound]),
    ],
  },
  {
    id: 'ld_5c44', fullName: 'Ruth Amari', email: 'ruth.amari@fieldstonegrocers.com', phone: '+1 (404) 555-0151',
    companyWebsite: 'https://fieldstonegrocers.com', linkedinUrl: 'https://linkedin.com/company/fieldstone-grocers',
    companyName: 'Fieldstone Grocers', role: 'Operations Lead', niche: 'E-commerce — grocery fulfilment',
    primaryService: 'Online ordering and same-day fulfilment for independent grocery co-operatives across the south-east',
    icpFitScore: 5, status: 'scored', scoredAt: '2026-08-24T15:02:00Z', durationMs: 6600, criteriaVersion: 'v4',
    icpFitReason: 'Half B2B and half consumer: they sell software to co-ops but the storefront is a shopper experience, so the must-have on business buyers only partially holds. Team size and the manual-picking pain point are both solid, and there is no outbound function anywhere on the site or the company page, which caps this in the middle of the range.',
    icebreaker: 'The line about pickers walking the same aisle three times stuck with me — most of the co-ops you sell into probably describe their supplier calls the same way. Is the co-op side of the business the one you are trying to grow this year?',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 46 employees.'),
      cr(C.b2b, 'must_have', 5, 'partial', 'Co-op software plus a consumer storefront.'),
      cr(C.pain, 'must_have', 4, 'met', '"Pickers walk the same aisle three times" on the ops page.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'Warehouse roles only.'),
      cr(C.outbound, 'nice_to_have', 2, 'not_met', 'No commercial team listed.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Retail operator.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '46 employees · Retail · Atlanta, GA', [C.team]),
      ev('website', 'Operations', 'Pickers walk the same aisle three times on an average order.', [C.pain]),
      ev('website', 'For co-ops', 'Bring your member network online in six weeks.', [C.b2b]),
    ],
  },
  {
    id: 'ld_5d19', fullName: 'Sofia Marchetti', email: 'sofia@loomfield.co', phone: '+1 (646) 555-0125',
    companyWebsite: 'https://loomfield.co', linkedinUrl: 'https://linkedin.com/company/loomfield',
    companyName: 'Loomfield', role: 'Founder', niche: 'E-commerce — apparel',
    primaryService: 'Direct-to-consumer knitwear',
    icpFitScore: 4, status: 'scored', scoredAt: '2026-08-24T09:26:00Z', durationMs: 3900, criteriaVersion: 'v4',
    icpFitReason: 'Consumer brand with 11 employees. The size band is met, but they do not sell to businesses and there is no sales function for us to support.',
    icebreaker: 'Your restock waitlist is doing a lot of work for a team of eleven. If you ever open a wholesale line, the buyer research side is where we would be useful.',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 11 employees.'),
      cr(C.b2b, 'must_have', 5, 'not_met', 'Direct-to-consumer only; no wholesale path.'),
      cr(C.pain, 'must_have', 4, 'partial', 'Manual restock waitlist mentioned in the FAQ.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'No open roles.'),
      cr(C.outbound, 'nice_to_have', 2, 'not_met', 'No sales team.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Brand, not an agency.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '11 employees · Apparel & Fashion · Brooklyn, NY', [C.team]),
      ev('website', 'FAQ — Restocks', 'We email the waitlist by hand the morning a colour comes back.', [C.pain]),
      ev('website', 'Shop', 'Cart, sizes, free returns — no trade or wholesale section found.', [C.b2b]),
    ],
  },
  {
    id: 'ld_0d76', fullName: 'Ayesha Kahn', email: 'ayesha@brightsalthealth.com', phone: '+1 (858) 555-0143',
    companyWebsite: 'https://brightsalthealth.com', linkedinUrl: 'https://linkedin.com/company/brightsalt-health',
    companyName: 'Brightsalt Health', role: 'COO', niche: 'Healthcare — dental group',
    primaryService: 'Nine-location dental practice group',
    icpFitScore: 3, status: 'scored', scoredAt: '2026-08-23T12:44:00Z', durationMs: 4200, criteriaVersion: 'v4',
    icpFitReason: 'A patient-facing practice group. Right headcount, wrong buyer: no business customers and nothing resembling a sales pipeline.',
    icebreaker: 'Your new-patient flow is unusually clear for a nine-location group. We work with teams selling to businesses, so this may be a miss — happy to be told so.',
    criteriaResults: [
      cr(C.team, 'must_have', 5, 'met', 'LinkedIn lists 84 employees.'),
      cr(C.b2b, 'must_have', 5, 'not_met', 'Patients are the customer.'),
      cr(C.pain, 'must_have', 4, 'not_met', 'No manual-workflow language on the site.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'Hygienist and front-desk roles.'),
      cr(C.outbound, 'nice_to_have', 2, 'not_met', 'No sales function.'),
      cr(C.agency, 'disqualifier', null, 'not_met', 'Care provider.'),
    ],
    evidence: [
      ev('linkedin', 'Company page — About', '84 employees · Dental Care · San Diego, CA', [C.team]),
      ev('website', 'New patients', 'Book your first visit online in under two minutes.', [C.b2b]),
    ],
  },
  {
    id: 'ld_6b23', fullName: 'Trevor Muller', email: 'trevor@pixelforge.studio', phone: '+1 (773) 555-0107',
    companyWebsite: 'https://pixelforge.studio', linkedinUrl: 'https://linkedin.com/company/pixelforge-collective',
    companyName: 'Pixelforge Collective', role: 'Principal', niche: 'Agency — creative resourcing',
    primaryService: 'Contract designers and creative staffing on retainer',
    icpFitScore: 2, status: 'scored', scoredAt: '2026-08-23T09:08:00Z', durationMs: 3600, criteriaVersion: 'v4',
    disqualified: true,
    icpFitReason: 'Disqualified: creative staffing on retainer. The disqualifier forces a low score regardless of the rest — they do sell to businesses and they do run outbound, but agencies resell this category and churn.',
    icebreaker: 'You place contract designers, which puts you on the other side of our ICP — sending this so it is on record rather than to pitch you.',
    criteriaResults: [
      cr(C.agency, 'disqualifier', null, 'met', 'Services page sells retained creative staffing.'),
      cr(C.team, 'must_have', 5, 'not_met', '6 employees plus a contractor bench.'),
      cr(C.b2b, 'must_have', 5, 'met', 'Sells to marketing teams.'),
      cr(C.pain, 'must_have', 4, 'partial', 'Talks about matching briefs to freelancers by hand.'),
      cr(C.hiring, 'nice_to_have', 3, 'not_met', 'No sales roles.'),
      cr(C.outbound, 'nice_to_have', 2, 'met', 'Cold outreach sequencer detected in the site footer.'),
    ],
    evidence: [
      ev('website', 'Services — Resourcing', 'A vetted bench of contract designers, billed monthly.', [C.agency]),
      ev('linkedin', 'Company page — About', '6 employees · Design Services · Chicago, IL', [C.team]),
      ev('website', 'Footer — script tag', 'Outreach sequencing pixel present on every page.', [C.outbound]),
    ],
  },
  {
    id: 'ld_1c04', fullName: 'Elliot Nash', email: 'elliot@fernwood.studio', phone: '+1 (971) 555-0172',
    companyWebsite: 'https://fernwood.studio', linkedinUrl: 'https://linkedin.com/company/fernwood-studio',
    companyName: 'Fernwood Studio', role: 'Managing Partner', niche: 'Agency — brand design',
    primaryService: 'Brand identity and packaging design',
    icpFitScore: null, status: 'processing', submittedAt: '2026-08-29T10:41:00Z', criteriaVersion: 'v4',
    icpFitReason: null, icebreaker: null, criteriaResults: [], evidence: [],
  },
  {
    id: 'ld_4f88', fullName: 'Hana Beck', email: 'hana@tidewater.finance', phone: '+1 (305) 555-0198',
    companyWebsite: 'https://tidewater.finance', linkedinUrl: 'https://linkedin.com/company/tidewater-treasury',
    companyName: 'Tidewater', role: 'Head of Growth', niche: 'Fintech — treasury',
    primaryService: 'Cash-flow forecasting for multi-entity finance teams',
    icpFitScore: null, status: 'processing', submittedAt: '2026-08-29T10:44:00Z', criteriaVersion: 'v4',
    icpFitReason: null, icebreaker: null, criteriaResults: [], evidence: [],
  },
];

export const sampleLead: SampleLead = {
  companyName: 'Northlight',
  niche: 'B2B SaaS — HR tech',
  results: {
    [C.team]: 'met',
    [C.b2b]: 'met',
    [C.pain]: 'met',
    [C.hiring]: 'met',
    [C.outbound]: 'partial',
    [C.agency]: 'not_met',
    [C.funding]: 'met',
  },
};

export const starterCriteria: StarterCriterion[] = [
  { name: 'Team size 10–200', type: 'must_have', weight: 5, source: 'both', description: 'Employee count on LinkedIn, or a team page on the site.' },
  { name: 'Sells to other businesses', type: 'must_have', weight: 5, source: 'website', description: 'Pricing, case studies or logos aimed at companies rather than consumers.' },
  { name: 'Hiring sales or SDR roles', type: 'nice_to_have', weight: 3, source: 'linkedin', description: 'Open SDR, AE or revenue roles in the last 90 days.' },
  { name: 'Staffing or recruiting agency', type: 'disqualifier', weight: null, source: 'both', description: 'Agencies resell this category and churn quickly.' },
];
